kind: Secret
apiVersion: v1
metadata:
  name: dockerlety
  namespace: ronlety
  uid: 21b60a7a-6189-4b52-9b93-9abdb85d2603
  resourceVersion: '1011168946'
  creationTimestamp: '2025-01-30T18:07:38Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2025-01-30T18:07:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:.dockerconfigjson': {}
        'f:type': {}
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodWIuZG9ja2VyLmNvbSI6eyJ1c2VybmFtZSI6InJvbmxldHk4NSIsInBhc3N3b3JkIjoiTWtvMDlpam5iaHU4JCIsImF1dGgiOiJjbTl1YkdWMGVUZzFPazFyYnpBNWFXcHVZbWgxT0NRPSIsImVtYWlsIjoicm9ubGV0eUBnbWFpbC5jb20ifX19
type: kubernetes.io/dockerconfigjson
