apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: tekton-triggers-sa 
  namespace: diploe2-gvmc 
--- 
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding 
metadata: 
  name: triggers-eventlistener-binding 
  namespace: diploe2-gvmc 
subjects: 
  - kind: ServiceAccount 
    name: tekton-triggers-sa 
    namespace: diploe2-gvmc
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: tekton-triggers-eventlistener-roles 
