apiVersion: v1
kind: ServiceAccount
metadata:
   name: tekton-triggers-sa
   namespace: diplo-rnl
--- 
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding 
metadata: 
  name: triggers-eventlistener-binding 
  namespace: diplo-rnl 
subjects: 
  - kind: ServiceAccount 
    name: tekton-triggers-sa 
    namespace: diplo-rnl
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: tekton-triggers-eventlistener-roles  
