apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata: 
  name: pipeline-cicd
  namespace: diplo-rnl
spec: 
  description: |
    clonar , empaquetar, construir y  desplegarla en un cluster Kubernetes
  params: 
    - name: repo-url 
      type: string 
    - name: maven-image 
      type: string
    - name: image-name
      type: string
    - name: deployment-name
      type: string
  workspaces: 
    - name: workspace 
    - name: maven-settings
    - name: dockerconfig
    - name: workspace-deploy
  tasks:
    - name: fetch-repository 
      taskRef: 
        kind: Task 
        name: git-clone 
      params: 
        - name: url   # <- this is the git-clone param  
          value: $(params.repo-url)   # <- a reference to param 
        - name: deleteExisting 
          value: "true"
      workspaces:
        - name: output # <- should be the same as the git-clone task 
          workspace: workspace # <- the workspace defined up 
    - name: maven
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: GOALS 
          value: 
            - -B 
            - -DskipTests 
            - clean 
            - package 
        - name: MAVEN_IMAGE 
          value: $(params.maven-image)  # <- same parameter as up 
      workspaces:
        - name: maven-settings 
          workspace: maven-settings 
        - name: source  # <- name of the workspace expected by the Task 
          workspace: workspace 
### buildimage & push
    - name: build-push-image
      taskRef:
        name: buildah
      runAfter:
        - maven
      params:
        - name: IMAGE 
          value: $(params.image-name)
          # ej. value: 'docker.io/cafaray/notificaciones:V2.2' 
        - name: TLSVERIFY 
          value: 'false' 
        - name: STORAGE_DRIVER 
          value: 'vfs'
      workspaces:
        - name: source  # <- name of the workspace expected by the Task 
          workspace: workspace 
        - name: dockerconfig
          workspace: dockerconfig
          
### deploy
    - name: deploy
      taskRef:
        name: kubernetes-actions
      runAfter:
        - build-push-image
      params:
        - name: script 
          value: | 
            kubectl delete deployment $(params.deployment-name) 
            kubectl create deployment $(params.deployment-name) --image=$(params.image-name)
            echo "----------" 
            kubectl get deployment
      workspaces:
        - name: kubeconfig-dir 
          workspace: workspace-deploy
        - name: manifest-dir 
          workspace: workspace-deploy
