apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: 
  generateName: pipelinerun-cicd- 
  namespace: diploe2-gvmc
spec: 
  serviceAccountName: tekton-sa 
  pipelineRef: 
    name: pipeline-cicd 
  params: 
    - name: repo-url 
      value: https://github.com/michcatg/diplomado.git
    - name: maven-image
      value: gcr.io/cloud-builders/mvn@sha256:8f38a2667125a8d83f6e1997847fedb6a06f041c90e2244884153d85d95f869b 
    - name: image-name
      value: docker.io/mitchcatg/coordlib-servicem5:v1.0.6
    - name: deployment-name
      value: coordlib-servicem5
  workspaces: 
    - name: maven-settings 
      configmap: 
        name: maven-settings 
    - name: workspace 
      persistentVolumeClaim: 
        claimName: workspace 
    - name: dockerconfig
      secret: 
        secretName: dockerconfig-secret
    - name: workspace-deploy
      emptyDir: {}
