apiVersion: v1
kind: Service
namespace: ronlety
metadata:
  name: web-app-service
spec:
   selector:
      app: web-app-ronlety
   ports:
      - protocol: TCP
        port: 8089
        targetPort: 8089
   type: ClusterIP

