apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-ronlety
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-ronlety
  template:
    metadata:
      labels:
        app: web-app-ronlety
    spec:
      containers:
        - name: web-app-ronlety
          image: ronlety85/proyecto:v8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          env:
            - name: TOMCAT_PORT
              value: '8089'
            - name: MONGO_URI
              value: "mongodb+srv://admindba:gNe7c2wLFBJKgIdZ@cluster0.vboxk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_DB
              value: "BookStore"
            - name: MONGO_USER
              value: "admindba"
            - name: MONGO_PWD
              value: "gNe7c2wLFBJKgIdZ"
