apiVersion: tekton.dev/v1beta1 
kind: TaskRun 
metadata:
  generateName: kubernetes-actions- 
  namespace: diplo-rnl
spec: 
  serviceAccountName: tekton
  taskRef: 
    name: kubernetes-actions 
  params: 
    - name: script 
      value: | 
        kubectl delete deployment lib-deployment 
        kubectl create deployment lib-deployment --image=docker.io/ronlety85/proyecto:latest
        kubectl get deployment 
  workspaces: 
    - name: kubeconfig-dir 
      emptyDir: {} 
    - name: manifest-dir 
      emptyDir: {} 
