apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig-secret
  namespace: diplo-rnl
stringData:
  config.json: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "bWl0Y2hjYXRnOjNvUjZGYmJZX0Vkb2NrZXJodWI="
        }
      }
    }
