apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
   generateName: buildah-run-
   namespace: diplo-rnl
spec:
   taskRef:
      name: buildah
   params:
      - name: IMAGE
        value: 'docker.io/ronlety85/proyecto:v9'
      - name: TLSVERIFY
        value: 'false'
      - name: STORAGE_DRIVER
        value: 'vfs'
   workspaces:
      - name: source
        persistentVolumeClaim:
             claimName: workspace-4
      - name: dockerconfig
        secret:
          secretName: dockerconfig-secret
