apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
   generateName: git-clone-
   namespace: diplo-rnl
spec:
   taskRef:
      kind: Task
      name: git-clone
   podTemplate:
      securityContext:
        fsGroup: 65532
   params:
   - name: url
     value: https://github.com/ronlety/proyecto25
   - name: deleteExisting
     value: "true"
   workspaces:
     - name: output
       persistentVolumeClaim:
          claimName: workspace
