apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-4
spec:
  storageClassName: civo-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 1Gi
  volumeMode: Filesystem

