spring:
  data:
    mongodb:
      uri: mongodb+srv://admindba:gNe7c2wLFBJKgIdZ@cluster0.vboxk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: proyecto
      username: admindba
      password: gNe7c2wLFBJKgIdZ
server:
  port: 8089
